name = "kharcha-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kharcha-db"
database_id = "a387d880-ba3e-4487-8455-11dc2311bd48"
migrations_dir = "migrations"
remote = true

[vars]
FRONTEND_URL = "https://kharcha-frontend.pages.dev"

[dev]
port = 8787
